set autoindent
filetype plugin indent on

set backspace=indent,eol,start

set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab

set background=dark
set modelines=0
set ruler

set list
set listchars=tab:▸\ ,trail:·,precedes:…,extends:…,nbsp:‗

set formatoptions+=n1

" don't leave swap files all over the place
set directory=~/.vim/swap//

set undofile
set undodir=~/.vim/undo//

set hidden

set showmatch
set showcmd
set incsearch

set completeopt=menu,menuone,noinsert,noselect,preview
set shiftround
